/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/male.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useAnimations, useGLTF } from '@react-three/drei'

const Male = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('./models/male.glb');
  const { actions, names } = useAnimations(animations, group);
  console.log(actions);

  // useEffect(() => {
  //   actions[names[0]].fadeIn(0.5).play();
  // }, [])

  return (
    <group {...props} dispose={null}>
      <mesh castShadow geometry={nodes.Male.geometry} material={nodes.Male.material} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

export default Male;
useGLTF.preload('./models/male.glb')
